# Generated by Django 4.2.4 on 2024-02-29 10:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webapp", "0002_fichier_redevance"),
    ]

    operations = [
        migrations.AddField(
            model_name="redevance",
            name="eobt",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="redevance",
            name="file_date",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="redevance",
            name="flight_state",
            field=models.CharField(default=1, max_length=25),
        ),
        migrations.AddField(
            model_name="redevance",
            name="flight_type",
            field=models.CharField(default=1, max_length=25),
        ),
        migrations.AddField(
            model_name="redevance",
            name="ifps_registration_mark",
            field=models.CharField(default=1, max_length=25),
        ),
        migrations.AddField(
            model_name="redevance",
            name="initial_flight_rule",
            field=models.CharField(default=1, max_length=25),
        ),
        migrations.AddField(
            model_name="redevance",
            name="nm_ifps_id",
            field=models.CharField(default=1, max_length=25),
        ),
        migrations.AddField(
            model_name="redevance",
            name="nm_tactical_id",
            field=models.IntegerField(default=1),
        ),
    ]
